name: CI for delta-sdk

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "Bun installed!"

      - name: Install dependencies
        run: bun install

      - name: Run unit tests
        run: bun run jest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "Bun installed!"

      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun run tsc

      - name: Build Docker image
        run: docker build -t delta-sdk .

      - name: Push Docker image to registry (optional)
        run: echo "This is where you would push the image to a registry"
